site_name: OSG Technology Area
site_url: https://opensciencegrid.github.io/technology/
repo_url: https://github.com/opensciencegrid/technology/
theme:
  name: material
  custom_dir: osgthedocs
  favicon: img/favicon.ico

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'
  - Software:
    - Packaging:
      - RPM Development Guide: 'software/rpm-development-guide.md'
      - OSG Build Tools: 'software/osg-build-tools.md'
      - Using Quilt: 'software/quilt.md'
      - Upcoming to Main: 'software/upcoming-to-main.md'
      - Koji Workflow: 'software/koji-workflow.md'
      - Creating the VO Client Package: 'software/create-vo-client.md'
      - Repository Management: 'software/repository-management.md'
      - Globus Mass Update Procedure: 'software/globus-mass-update-procedure.md'
      - Resurrecting Epel Packages: 'software/resurrecting-epel-packages.md'
      - Koji Mass Rebuilds: 'software/koji-mass-rebuilds.md'
    - Development:
      - Development Process: 'software/development-process.md'
      - Git Software Development Process: 'software/git-software-development.md'
      - CE Scale Testing: 'software/ce-test-scaling.md'
      - IPv6 Testing: 'software/ipv6-testing.md'
    - Software Support: 'policy/software-support.md'
    - Effort Tracking: 'software/effort-tracking.md'
    - Release Planning: 'software/release-planning.md'
    - New Team Member: 'software/new-team-member.md'
  - Release:
    - How to Cut a Release: 'release/cut-sw-release.md'
    - How to Cut a Data Release: 'release/cut-data-release.md'
    - Release Policy: 'release/release-policy.md'
    - Release Schedule: 'release/release-schedule.md'
    - New Release Series: 'release/new-release-series.md'
    - Old Release Series Removal: 'release/old-release-removal.md'
    - ITB Prerelease Testing: 'release/itb-testing.md'
    - Empty Packages: 'release/empty-pkgs.md'
    - Acceptance Testing: 'release/acceptance-testing.md'
  - Policy:
    - 'Service Migrations - Spring 2018': 'policy/service-migrations-spring-2018.md'
    - 'GUMS Retirement': 'policy/gums-retire.md'
    - 'BeStMan2 Retirement': 'policy/bestman2-retire.md'
    - 'VOMS Admin Retirement': 'policy/voms-admin-retire.md'
    - 'Release Series Support': 'policy/release-series.md'
    - 'Globus Toolkit Support': 'policy/globus-toolkit.md'
    - 'OASIS Repository Mirroring': 'policy/external-oasis-repos.md'
    - 'Flexible Release Model': 'policy/flexible-release-model.md'
  - Infrastructure:
    - Koji Restore Recipe: 'infrastructure/koji-restore-recipe.md'
    - Koji-Hub Setup: 'infrastructure/koji-hub-setup.md'
    - Koji Infrastructure Overview: 'infrastructure/koji-inf-overview.md'
    - Koji Policy Writing: 'infrastructure/koji-policy-writing.md'
    - Koji User Management: 'infrastructure/koji-user-management.md'
    - Madison ITB: 'infrastructure/madison-itb.md'
  - Documentation:
    - Writing Documentation: 'documentation/writing-documentation.md'
    - Reviewing Documentation: 'documentation/reviewing-documentation.md'
    - Markdown Style Guide: 'documentation/style-guide.md'
    - Creating a New Area: 'documentation/new-doc-area.md'
    - Migrating Documents to Markdown: 'documentation/markdown-migration.md'
  - Historical Information:
    - Koji Initial Install: 'infrastructure/koji-initial-install.md'
  - Historical Transitions:
    - 'SHA-2 Support': 'projects/sha2-support.md'
  - Meetings:
    - July 16, 2018: 'meetings/2018/TechArea20180716.md'
    - July 2, 2018: 'meetings/2018/TechArea20180702.md'
    - June 25, 2018: 'meetings/2018/TechArea20180625.md'
    - June 18, 2018: 'meetings/2018/TechArea20180618.md'
    - June 11, 2018: 'meetings/2018/TechArea20180611.md'
    - June 4, 2018: 'meetings/2018/TechArea20180604.md'
    - May 29, 2018: 'meetings/2018/TechArea20180529.md'
    - May 14, 2018: 'meetings/2018/TechArea20180514.md'
    - May 7, 2018: 'meetings/2018/TechArea20180507.md'
    - April 30, 2018: 'meetings/2018/TechArea20180430.md'
    - April 23, 2018: 'meetings/2018/TechArea20180423.md'
    - April 16, 2018: 'meetings/2018/TechArea20180416.md'
    - April 9, 2018: 'meetings/2018/TechArea20180409.md'
    - April 2, 2018: 'meetings/2018/TechArea20180402.md'
    - March 12, 2018: 'meetings/2018/TechArea20180312.md'
    - March 5, 2018: 'meetings/2018/TechArea20180305.md'
    - February 26, 2018: 'meetings/2018/TechArea20180226.md'
    - February 19, 2018: 'meetings/2018/TechArea20180219.md'
    - February 12, 2018: 'meetings/2018/TechArea20180212.md'
    - February 5, 2018: 'meetings/2018/TechArea20180205.md'
    - January 29, 2018: 'meetings/2018/TechArea20180129.md'
    - January 22, 2018: 'meetings/2018/TechArea20180122.md'
    - January 8, 2018: 'meetings/2018/TechArea20180108.md'
    - January 2, 2018: 'meetings/2018/TechArea20180102.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - osg_markdown.colors

