site_name: OSG Technology Area
site_url: https://opensciencegrid.github.io/technology/
repo_url: https://github.com/opensciencegrid/technology/
theme:
  name: material
  custom_dir: osgthedocs
  favicon: img/favicon.ico

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'
  - Software:
    - Packaging:
      - RPM Development Guide: 'software/rpm-development-guide.md'
      - OSG Build Tools: 'software/osg-build-tools.md'
      - Using Quilt: 'software/quilt.md'
      - Upcoming to Main: 'software/upcoming-to-main.md'
      - Koji Workflow: 'software/koji-workflow.md'
      - Creating the VO Client Package: 'software/create-vo-client.md'
      - Container Development Guide: 'software/container-development-guide.md'
      - Repository Management: 'software/repository-management.md'
      - Globus Mass Update Procedure: 'software/globus-mass-update-procedure.md'
      - Resurrecting Epel Packages: 'software/resurrecting-epel-packages.md'
      - Koji Mass Rebuilds: 'software/koji-mass-rebuilds.md'
    - Development:
      - Development Process: 'software/development-process.md'
      - Git Software Development Process: 'software/git-software-development.md'
      - CE Scale Testing: 'software/ce-test-scaling.md'
      - IPv6 Testing: 'software/ipv6-testing.md'
      - How to Request Tokens: 'software/requesting-tokens.md'
    - Software Support: 'policy/software-support.md'
    - Effort Tracking: 'software/effort-tracking.md'
    - Release Planning: 'software/release-planning.md'
    - New Team Member: 'software/new-team-member.md'
  - Release:
    - How to Cut a Release: 'release/cut-sw-release.md'
    - How to Cut a Data Release: 'release/cut-data-release.md'
    - Ready for Testing Announcements: 'release/announce-rft-packages.md'
    - New Release Series: 'release/new-release-series.md'
    - Old Release Series Removal: 'release/old-release-removal.md'
    - ITB Prerelease Testing: 'release/itb-testing.md'
    - Empty Packages: 'release/empty-pkgs.md'
    - Acceptance Testing: 'release/acceptance-testing.md'
  - Policy:
    - GridFTP and GSI Migration: 'policy/gridftp-gsi-migration.md'
    - Campus Cyberinfrastructure: 'policy/campus-cyberinfrastructure.md'
    - CREAM-CE Support: 'policy/cream-support.md'
    - 'Release Series Support': 'policy/release-series.md'
    - 'Globus Toolkit Support': 'policy/globus-toolkit.md'
    - 'OASIS Repository Mirroring': 'policy/external-oasis-repos.md'
    - 'Flexible Release Model': 'policy/flexible-release-model.md'
    - Software Release Policy: 'policy/software-release.md'
    - Container Release Policy: 'policy/container-release.md'
    - 'Community Testing': 'policy/community-testing.md'
    - Registering in COManage: 'policy/comanage-instructions-user.md'
    - Approving COManage Registrations: 'policy/comanage-instructions-admin.md'
  - Documentation:
    - Writing Documentation: 'documentation/writing-documentation.md'
    - Reviewing Documentation: 'documentation/reviewing-documentation.md'
    - Markdown Style Guide: 'documentation/style-guide.md'
    - Creating a New Area: 'documentation/new-doc-area.md'
  - Historical Transitions:
    - Service Migrations - Spring 2018: 'policy/service-migrations-spring-2018.md'
    - GUMS Retirement: 'policy/gums-retire.md'
    - BeStMan2 Retirement: 'policy/bestman2-retire.md'
    - VOMS Admin Retirement: 'policy/voms-admin-retire.md'
    - SHA-2 Support: 'projects/sha2-support.md'
    - Migrating Documents to Markdown: 'documentation/markdown-migration.md'
  - Meetings:
    - August 10, 2020: 'meetings/2020/TechArea20200810.md'
    - August 3, 2020: 'meetings/2020/TechArea20200803.md'
    - July 27, 2020: 'meetings/2020/TechArea20200727.md'
    - July 20, 2020: 'meetings/2020/TechArea20200720.md'
    - July 13, 2020: 'meetings/2020/TechArea20200713.md'
    - July 6, 2020: 'meetings/2020/TechArea20200706.md'
    - June 29, 2020: 'meetings/2020/TechArea20200629.md'
    - June 22, 2020: 'meetings/2020/TechArea20200622.md'
    - June 15, 2020: 'meetings/2020/TechArea20200615.md'
    - June 8, 2020: 'meetings/2020/TechArea20200608.md'
    - June 1, 2020: 'meetings/2020/TechArea20200601.md'
    - May 18, 2020: 'meetings/2020/TechArea20200518.md'
    - May 11, 2020: 'meetings/2020/TechArea20200511.md'
    - May 4, 2020: 'meetings/2020/TechArea20200504.md'
    - April 27, 2020: 'meetings/2020/TechArea20200427.md'
    - April 20, 2020: 'meetings/2020/TechArea20200420.md'
    - April 13, 2020: 'meetings/2020/TechArea20200413.md'
    - April 6, 2020: 'meetings/2020/TechArea20200406.md'
    - March 30, 2020: 'meetings/2020/TechArea20200330.md'
    - March 23, 2020: 'meetings/2020/TechArea20200323.md'
    - March 16, 2020: 'meetings/2020/TechArea20200316.md'
    - March 9, 2020: 'meetings/2020/TechArea20200309.md'
    - March 2, 2020: 'meetings/2020/TechArea20200302.md'
    - February 24, 2020: 'meetings/2020/TechArea20200224.md'
    - February 17, 2020: 'meetings/2020/TechArea20200217.md'
    - February 10, 2020: 'meetings/2020/TechArea20200210.md'
    - February 3, 2020: 'meetings/2020/TechArea20200203.md'
    - January, 27 2020: 'meetings/2020/TechArea20200127.md'
    - January, 13 2020: 'meetings/2020/TechArea20200113.md'
    - January, 6 2020: 'meetings/2020/TechArea20200106.md'
    - December, 16 2019: 'meetings/2019/TechArea20191216.md'
    - December, 9 2019: 'meetings/2019/TechArea20191209.md'
    - December, 2 2019: 'meetings/2019/TechArea20191202.md'
    - November, 25 2019: 'meetings/2019/TechArea20191125.md'
    - November, 18 2019: 'meetings/2019/TechArea20191118.md'
    - November, 11 2019: 'meetings/2019/TechArea20191111.md'
    - November, 4 2019: 'meetings/2019/TechArea20191104.md'
    - October, 28 2019: 'meetings/2019/TechArea20191028.md'
    - October, 21 2019: 'meetings/2019/TechArea20191021.md'
    - October, 14 2019: 'meetings/2019/TechArea20191014.md'
    - October, 7 2019: 'meetings/2019/TechArea20191007.md'
    - September, 30 2019: 'meetings/2019/TechArea20190930.md'
    - September, 23 2019: 'meetings/2019/TechArea20190923.md'
    - September, 16 2019: 'meetings/2019/TechArea20190916.md'
    - September, 9 2019: 'meetings/2019/TechArea20190909.md'
    - August, 26 2019: 'meetings/2019/TechArea20190826.md'
    - August, 19 2019: 'meetings/2019/TechArea20190819.md'
    - August, 12 2019: 'meetings/2019/TechArea20190812.md'
    - August, 5 2019: 'meetings/2019/TechArea20190805.md'
    - July 29, 2019: 'meetings/2019/TechArea20190729.md'
    - July 22, 2019: 'meetings/2019/TechArea20190722.md'
    - July 8, 2019: 'meetings/2019/TechArea20190708.md'
    - July 1, 2019: 'meetings/2019/TechArea20190701.md'
    - June 24, 2019: 'meetings/2019/TechArea20190624.md'
    - June 17, 2019: 'meetings/2019/TechArea20190617.md'
    - June 10, 2019: 'meetings/2019/TechArea20190610.md'
    - June 3, 2019: 'meetings/2019/TechArea20190603.md'
    - May 28, 2019: 'meetings/2019/TechArea20190528.md'
    - May 13, 2019: 'meetings/2019/TechArea20190513.md'
    - May 6, 2019: 'meetings/2019/TechArea20190506.md'
    - April 29, 2019: 'meetings/2019/TechArea20190429.md'
    - April 22, 2019: 'meetings/2019/TechArea20190422.md'
    - April 15, 2019: 'meetings/2019/TechArea20190415.md'
    - April 8, 2019: 'meetings/2019/TechArea20190408.md'
    - April 1, 2019: 'meetings/2019/TechArea20190401.md'
    - March 25, 2019: 'meetings/2019/TechArea20190325.md'
    - March 11, 2019: 'meetings/2019/TechArea20190311.md'
    - March 4, 2019: 'meetings/2019/TechArea20190304.md'
    - February 25, 2019: 'meetings/2019/TechArea20190225.md'
    - February 18, 2019: 'meetings/2019/TechArea20190218.md'
    - February 11, 2019: 'meetings/2019/TechArea20190211.md'
    - February 4, 2019: 'meetings/2019/TechArea20190204.md'
    - January 28, 2019: 'meetings/2019/TechArea20190128.md'
    - January 22, 2019: 'meetings/2019/TechArea20190122.md'
    - January 14, 2019: 'meetings/2019/TechArea20190114.md'
    - January 7, 2019: 'meetings/2019/TechArea20190107.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - toc:
      permalink: True

