site_name: OSG Technology Area
site_url: https://opensciencegrid.github.io/technology
repo_url: https://github.com/opensciencegrid/technology
theme: readthedocs
theme_dir: osgthedocs

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'
  - Contact Us: 'contact.md'
  - Meeting Notes: 'meetings.md'
  - February 27, 2017: 'meetings/2017/TechArea20170227.md'
  - April 17, 2017: 'meetings/2017/TechArea20170417.md'
  - Policy:
    - 'VOMS Admin Retirement': 'policy/voms-admin-retire.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors
