site_name: OSG Technology Area
site_url: https://opensciencegrid.github.io/technology
repo_url: https://github.com/opensciencegrid/technology
theme: readthedocs
theme_dir: osgthedocs

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'
  - Contact Us: 'contact.md'
  - Meeting Notes: 'meetings.md'
  - Policy:
    - 'VOMS Admin Retirement': 'policy/voms-admin-retire.md'
    - 'Release Series Support': 'policy/release-series.md'
  - February 27, 2017: 'meetings/2017/TechArea20170227.md'
  - April 17, 2017: 'meetings/2017/TechArea20170417.md'
  - April 24, 2017: 'meetings/2017/TechArea20170424.md'
  - May 1, 2017: 'meetings/2017/TechArea20170501.md'
  - May 8, 2017: 'meetings/2017/TechArea20170508.md'
  - May 15, 2017: 'meetings/2017/TechArea20170515.md'
  - May 22, 2017: 'meetings/2017/TechArea20170522.md'
  - May 30, 2017: 'meetings/2017/TechArea20170530.md'    

markdown_extensions:
  - admonition

