site_name: OSG Technology Area
site_url: https://opensciencegrid.github.io/technology
repo_url: https://github.com/opensciencegrid/technology
theme: readthedocs
theme_dir: osgthedocs

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'
  - Software:
    - Development Process: 'software/development-process.md'
    - Migrating Documents to Markdown: 'software/markdown-migration.md'
    - Koji Workflow: 'software/koji-workflow.md'
    - New Team Member: 'software/new-team-member.md'
    - Repository Management: 'software/repository-management.md'
    - CE Scale Testing: 'software/ce-test-scaling.md'
    - RPM Development Guide: 'software/rpm-development-guide.md'
    - Upcoming to Main: 'software/upcoming-to-main.md'
    - Software Support: 'policy/software-support.md'
    - Effort Tracking: 'software/effort-tracking.md'
    - Release Planning: 'software/release-planning.md'
    - Globus Mass Update Procedure: 'software/globus-mass-update-procedure.md'
    - Git Software Development Process: 'software/git-software-development.md'
    - OSG Build Tools: 'software/osg-build-tools.md'
    - Resurrecting Epel Packages: 'software/resurrecting-epel-packages.md'
    - Koji Mass Rebuilds: 'software/koji-mass-rebuilds.md'
    - Creating the VO Client Package: 'software/create-vo-client.md'
  - Release:
    - How to Cut a Release: 'release/cut-sw-release.md'
    - How to Cut a Data Release: 'release/cut-data-release.md'
    - Release Policy: 'release/release-policy.md'
    - Release Schedule: 'release/release-schedule.md'
    - New Release Series: 'release/new-release-series.md'
    - Old Release Series Removal: 'release/old-release-removal.md'
    - HTCondor Prerelease Testing: 'release/condor-itb-testing.md'
    - VO Package Testing: 'release/testing-vo-package.md'
  - Policy:
    - 'GUMS Retirement': 'policy/gums-retire.md'
    - 'BeStMan2 Retirement': 'policy/bestman2-retire.md'
    - 'VOMS Admin Retirement': 'policy/voms-admin-retire.md'
    - 'Release Series Support': 'policy/release-series.md'
    - 'Globus Toolkit Support': 'policy/globus-toolkit.md'
    - 'OASIS Repository Mirroring': 'docs/policy/external-oasis-repos.md'
  - Infrastructure:
    - Koji Restore Recipe: 'infrastructure/koji-restore-recipe.md'
    - Koji-Hub Setup: 'infrastructure/koji-hub-setup.md'
    - Koji Infrastructure Overview: 'infrastructure/koji-inf-overview.md'
    - Koji Policy Writing: 'infrastructure/koji-policy-writing.md'
    - Madison ITB: 'infrastructure/madison-itb.md'
  - Documentation:
    - Writing Documentation: 'documentation/writing-documentation.md'
  - Historical Information:
    - Koji Initial Install: 'infrastructure/koji-initial-install.md'
  - Historical Transitions:
    - 'SHA-2 Support': 'projects/sha2-support.md'
  - February 27, 2017: 'meetings/2017/TechArea20170227.md'
  - April 17, 2017: 'meetings/2017/TechArea20170417.md'
  - April 24, 2017: 'meetings/2017/TechArea20170424.md'
  - May 1, 2017: 'meetings/2017/TechArea20170501.md'
  - May 8, 2017: 'meetings/2017/TechArea20170508.md'
  - May 15, 2017: 'meetings/2017/TechArea20170515.md'
  - May 22, 2017: 'meetings/2017/TechArea20170522.md'
  - May 30, 2017: 'meetings/2017/TechArea20170530.md'
  - June 6, 2017: 'meetings/2017/TechArea20170605.md'
  - June 12, 2017: 'meetings/2017/TechArea20170612.md'
  - June 19, 2017: 'meetings/2017/TechArea20170619.md'
  - June 26, 2017: 'meetings/2017/TechArea20170626.md'
  - July 3, 2017: 'meetings/2017/TechArea20170703.md'
  - July 10, 2017: 'meetings/2017/TechArea20170710.md'
  - July 17, 2017: 'meetings/2017/TechArea20170717.md'
  - July 24, 2017: 'meetings/2017/TechArea20170724.md'
  - July 31, 2017: 'meetings/2017/TechArea20170731.md'
  - August 7, 2017: 'meetings/2017/TechArea20170807.md'
  - August 14, 2017: 'meetings/2017/TechArea20170814.md'
  - August 28, 2017: 'meetings/2017/TechArea20170828.md'
  - September 5, 2017: 'meetings/2017/TechArea20170905.md'
  - September 11, 2017: 'meetings/2017/TechArea20170911.md'
  - September 18, 2017: 'meetings/2017/TechArea20170918.md'
  - September 25, 2017: 'meetings/2017/TechArea20170925.md'
  - October 2, 2017: 'meetings/2017/TechArea20171002.md'
  - October 9, 2017: 'meetings/2017/TechArea20171009.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - osg_markdown.colors

