site_name: OSG Technology Area
site_url: https://opensciencegrid.github.io/technology/
repo_url: https://github.com/opensciencegrid/technology/
theme:
  name: material
  custom_dir: osgthedocs
  favicon: img/favicon.ico

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'
  - Software:
    - Packaging:
      - RPM Development Guide: 'software/rpm-development-guide.md'
      - OSG Build Tools: 'software/osg-build-tools.md'
      - Using Quilt: 'software/quilt.md'
      - Upcoming to Main: 'software/upcoming-to-main.md'
      - Koji Workflow: 'software/koji-workflow.md'
      - Creating the VO Client Package: 'software/create-vo-client.md'
      - Repository Management: 'software/repository-management.md'
      - Globus Mass Update Procedure: 'software/globus-mass-update-procedure.md'
      - Resurrecting Epel Packages: 'software/resurrecting-epel-packages.md'
      - Koji Mass Rebuilds: 'software/koji-mass-rebuilds.md'
    - Development:
      - Development Process: 'software/development-process.md'
      - Git Software Development Process: 'software/git-software-development.md'
      - CE Scale Testing: 'software/ce-test-scaling.md'
      - IPv6 Testing: 'software/ipv6-testing.md'
    - Software Support: 'policy/software-support.md'
    - Effort Tracking: 'software/effort-tracking.md'
    - Release Planning: 'software/release-planning.md'
    - New Team Member: 'software/new-team-member.md'
  - Release:
    - How to Cut a Release: 'release/cut-sw-release.md'
    - How to Cut a Data Release: 'release/cut-data-release.md'
    - New Release Series: 'release/new-release-series.md'
    - Old Release Series Removal: 'release/old-release-removal.md'
    - ITB Prerelease Testing: 'release/itb-testing.md'
    - Empty Packages: 'release/empty-pkgs.md'
    - Acceptance Testing: 'release/acceptance-testing.md'
  - Policy:
    - CREAM-CE Support: 'policy/cream-support.md'
    - 'Service Migrations - Spring 2018': 'policy/service-migrations-spring-2018.md'
    - 'GUMS Retirement': 'policy/gums-retire.md'
    - 'BeStMan2 Retirement': 'policy/bestman2-retire.md'
    - 'VOMS Admin Retirement': 'policy/voms-admin-retire.md'
    - 'Release Series Support': 'policy/release-series.md'
    - 'Globus Toolkit Support': 'policy/globus-toolkit.md'
    - 'OASIS Repository Mirroring': 'policy/external-oasis-repos.md'
    - 'Flexible Release Model': 'policy/flexible-release-model.md'
    - Software Release Policy: 'policy/software-release.md'
    - Container Release Policy: 'policy/container-release.md'
    - 'Community Testing': 'policy/community-testing.md'
  - Documentation:
    - Writing Documentation: 'documentation/writing-documentation.md'
    - Reviewing Documentation: 'documentation/reviewing-documentation.md'
    - Markdown Style Guide: 'documentation/style-guide.md'
    - Creating a New Area: 'documentation/new-doc-area.md'
  - Historical Transitions:
    - 'SHA-2 Support': 'projects/sha2-support.md'
    - Migrating Documents to Markdown: 'documentation/markdown-migration.md'
  - Meetings:
    - March 11, 2019: 'meetings/2019/TechArea20190311.md'
    - March 4, 2019: 'meetings/2019/TechArea20190304.md'
    - February 25, 2019: 'meetings/2019/TechArea20190225.md'
    - February 18, 2019: 'meetings/2019/TechArea20190218.md'
    - February 11, 2019: 'meetings/2019/TechArea20190211.md'
    - February 4, 2019: 'meetings/2019/TechArea20190204.md'
    - January 28, 2019: 'meetings/2019/TechArea20190128.md'
    - January 22, 2019: 'meetings/2019/TechArea20190122.md'
    - January 14, 2019: 'meetings/2019/TechArea20190114.md'
    - January 7, 2019: 'meetings/2019/TechArea20190107.md'
    - December 17, 2018: 'meetings/2018/TechArea20181217.md'
    - December 10, 2018: 'meetings/2018/TechArea20181210.md'
    - December 3, 2018: 'meetings/2018/TechArea20181203.md'
    - November 26, 2018: 'meetings/2018/TechArea20181126.md'
    - November 19, 2018: 'meetings/2018/TechArea20181119.md'
    - November 12, 2018: 'meetings/2018/TechArea20181112.md'
    - November 5, 2018: 'meetings/2018/TechArea20181105.md'
    - October 29, 2018: 'meetings/2018/TechArea20181029.md'
    - October 22, 2018: 'meetings/2018/TechArea20181022.md'
    - October 15, 2018: 'meetings/2018/TechArea20181015.md'
    - October 8, 2018: 'meetings/2018/TechArea20181008.md'
    - October 1, 2018: 'meetings/2018/TechArea20181001.md'
    - September 24, 2018: 'meetings/2018/TechArea20180924.md'
    - September 17, 2018: 'meetings/2018/TechArea20180917.md'
    - September 10, 2018: 'meetings/2018/TechArea20180910.md'
    - August 27, 2018: 'meetings/2018/TechArea20180827.md'
    - August 20, 2018: 'meetings/2018/TechArea20180820.md'
    - August 13, 2018: 'meetings/2018/TechArea20180813.md'
    - August 6, 2018: 'meetings/2018/TechArea20180806.md'
    - July 30, 2018: 'meetings/2018/TechArea20180730.md'
    - July 23, 2018: 'meetings/2018/TechArea20180723.md'
    - July 16, 2018: 'meetings/2018/TechArea20180716.md'
    - July 2, 2018: 'meetings/2018/TechArea20180702.md'
    - June 25, 2018: 'meetings/2018/TechArea20180625.md'
    - June 18, 2018: 'meetings/2018/TechArea20180618.md'
    - June 11, 2018: 'meetings/2018/TechArea20180611.md'
    - June 4, 2018: 'meetings/2018/TechArea20180604.md'
    - May 29, 2018: 'meetings/2018/TechArea20180529.md'
    - May 14, 2018: 'meetings/2018/TechArea20180514.md'
    - May 7, 2018: 'meetings/2018/TechArea20180507.md'
    - April 30, 2018: 'meetings/2018/TechArea20180430.md'
    - April 23, 2018: 'meetings/2018/TechArea20180423.md'
    - April 16, 2018: 'meetings/2018/TechArea20180416.md'
    - April 9, 2018: 'meetings/2018/TechArea20180409.md'
    - April 2, 2018: 'meetings/2018/TechArea20180402.md'
    - March 12, 2018: 'meetings/2018/TechArea20180312.md'
    - March 5, 2018: 'meetings/2018/TechArea20180305.md'
    - February 26, 2018: 'meetings/2018/TechArea20180226.md'
    - February 19, 2018: 'meetings/2018/TechArea20180219.md'
    - February 12, 2018: 'meetings/2018/TechArea20180212.md'
    - February 5, 2018: 'meetings/2018/TechArea20180205.md'
    - January 29, 2018: 'meetings/2018/TechArea20180129.md'
    - January 22, 2018: 'meetings/2018/TechArea20180122.md'
    - January 8, 2018: 'meetings/2018/TechArea20180108.md'
    - January 2, 2018: 'meetings/2018/TechArea20180102.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
  - osg_markdown.colors

