site_name: OSG Technology Area
site_url: https://opensciencegrid.github.io/technology/
repo_url: https://github.com/opensciencegrid/technology/
theme:
  name: material
  custom_dir: osgthedocs
  favicon: img/favicon.ico

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'
  - Software:
    - Packaging:
      - RPM Development Guide: 'software/rpm-development-guide.md'
      - OSG Build Tools: 'software/osg-build-tools.md'
      - Using Quilt: 'software/quilt.md'
      - Upcoming to Main: 'software/upcoming-to-main.md'
      - Koji Workflow: 'software/koji-workflow.md'
      - Creating the VO Client Package: 'software/create-vo-client.md'
      - Repository Management: 'software/repository-management.md'
      - Globus Mass Update Procedure: 'software/globus-mass-update-procedure.md'
      - Resurrecting Epel Packages: 'software/resurrecting-epel-packages.md'
      - Koji Mass Rebuilds: 'software/koji-mass-rebuilds.md'
    - Development:
      - Development Process: 'software/development-process.md'
      - Git Software Development Process: 'software/git-software-development.md'
      - CE Scale Testing: 'software/ce-test-scaling.md'
      - IPv6 Testing: 'software/ipv6-testing.md'
    - Software Support: 'policy/software-support.md'
    - Effort Tracking: 'software/effort-tracking.md'
    - Release Planning: 'software/release-planning.md'
    - New Team Member: 'software/new-team-member.md'
  - Release:
    - How to Cut a Release: 'release/cut-sw-release.md'
    - How to Cut a Data Release: 'release/cut-data-release.md'
    - New Release Series: 'release/new-release-series.md'
    - Old Release Series Removal: 'release/old-release-removal.md'
    - ITB Prerelease Testing: 'release/itb-testing.md'
    - Empty Packages: 'release/empty-pkgs.md'
    - Acceptance Testing: 'release/acceptance-testing.md'
  - Policy:
    - CREAM-CE Support: 'policy/cream-support.md'
    - 'Service Migrations - Spring 2018': 'policy/service-migrations-spring-2018.md'
    - 'GUMS Retirement': 'policy/gums-retire.md'
    - 'BeStMan2 Retirement': 'policy/bestman2-retire.md'
    - 'VOMS Admin Retirement': 'policy/voms-admin-retire.md'
    - 'Release Series Support': 'policy/release-series.md'
    - 'Globus Toolkit Support': 'policy/globus-toolkit.md'
    - 'OASIS Repository Mirroring': 'policy/external-oasis-repos.md'
    - 'Flexible Release Model': 'policy/flexible-release-model.md'
    - Software Release Policy: 'policy/software-release.md'
    - Container Release Policy: 'policy/container-release.md'
    - 'Community Testing': 'policy/community-testing.md'
  - Documentation:
    - Writing Documentation: 'documentation/writing-documentation.md'
    - Reviewing Documentation: 'documentation/reviewing-documentation.md'
    - Markdown Style Guide: 'documentation/style-guide.md'
    - Creating a New Area: 'documentation/new-doc-area.md'
  - Historical Transitions:
    - 'SHA-2 Support': 'projects/sha2-support.md'
    - Migrating Documents to Markdown: 'documentation/markdown-migration.md'
  - Meetings:
    - July 8, 2019: 'meetings/2019/TechArea20190708.md'
    - July 1, 2019: 'meetings/2019/TechArea20190701.md'
    - June 24, 2019: 'meetings/2019/TechArea20190624.md'
    - June 17, 2019: 'meetings/2019/TechArea20190617.md'
    - June 10, 2019: 'meetings/2019/TechArea20190610.md'
    - June 3, 2019: 'meetings/2019/TechArea20190603.md'
    - May 28, 2019: 'meetings/2019/TechArea20190528.md'
    - May 13, 2019: 'meetings/2019/TechArea20190513.md'
    - May 6, 2019: 'meetings/2019/TechArea20190506.md'
    - April 29, 2019: 'meetings/2019/TechArea20190429.md'
    - April 22, 2019: 'meetings/2019/TechArea20190422.md'
    - April 15, 2019: 'meetings/2019/TechArea20190415.md'
    - April 8, 2019: 'meetings/2019/TechArea20190408.md'
    - April 1, 2019: 'meetings/2019/TechArea20190401.md'
    - March 25, 2019: 'meetings/2019/TechArea20190325.md'
    - March 11, 2019: 'meetings/2019/TechArea20190311.md'
    - March 4, 2019: 'meetings/2019/TechArea20190304.md'
    - February 25, 2019: 'meetings/2019/TechArea20190225.md'
    - February 18, 2019: 'meetings/2019/TechArea20190218.md'
    - February 11, 2019: 'meetings/2019/TechArea20190211.md'
    - February 4, 2019: 'meetings/2019/TechArea20190204.md'
    - January 28, 2019: 'meetings/2019/TechArea20190128.md'
    - January 22, 2019: 'meetings/2019/TechArea20190122.md'
    - January 14, 2019: 'meetings/2019/TechArea20190114.md'
    - January 7, 2019: 'meetings/2019/TechArea20190107.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true):
  - osg_markdown.colors

