name: Build, test, and deploy static MkDocs pages
on: [push, pull_request]

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: opensciencegrid/doc-ci-scripts
          path: doc-ci-scripts
      - name: Build MkDocs pages
        uses: docker://squidfunk/mkdocs-material:6.1.4
        timeout-minutes: 1
        with:
          args: >-
            build
            --verbose
            --strict
      - name: Test links
        timeout-minutes: 10
        uses: docker://klakegg/html-proofer:3.16.0
        with:
          args: >-
            --allow-hash-href
            --check-html
      - name: Deploy MkDocs pages
        if: github.event_name == 'push' && startsWith(github.repository, 'opensciencegrid/')
        uses: docker://squidfunk/mkdocs-material:6.1.4
        with:
          args: >-
            gh-deploy
            --verbose
